### ISSUE TITLE
survey.end_data의 default에 함수가 아닌 값이 들어갔어요!

### ISSUE THREAD

**Issue by itsnamgyu** [hyungi/survey_dot_com#5]
원래 요렇게 함수가 들어가야되는데
https://github.com/hyungi/survey_dot_com/blob/2593ddb92d3d880d2a5714d3781b703237ae9044/survey/models.py#L22

요렇게 (함수 호출 후 반환된) 값이 들어갔어요!
https://github.com/hyungi/survey_dot_com/blob/2593ddb92d3d880d2a5714d3781b703237ae9044/survey/models.py#L23

*()의 유무를 유심희 보십쇼...*

이렇게 하면 `python manage.py makemigrations`를 할때마다 현재 날짜 + 10일에 해당하는 날짜로 바뀌는 migration이 만들어지고, 게시물을 올릴 때 현재 날짜 + 10일이 들어가지 않고 makemigrations에서 입력된 날짜 + 10일이 입력돼요!

현재 날짜 + 10일을 반환하는 함수를 만들어서 그걸 넘겨주면 될거같아욥

**Comment by itsnamgyu** [comment]
개발용 sqlite3 db 설정을 추가했으면 하는 이유가, 요런 문제를 해결할려고 코드를 테스트할 때 postgresql에서 migrate 해버렸는데 알고보니까 잘못 고쳤으면 다시 되돌리기가 힘든 고런 이유가 있어요! (migrate를 되돌리는 방법도 있긴 하겠지만 ㅇㅅㅇ)

sqlite 설정 추가한 후에 이슈 해결하도록 하겠읍니당

**Comment by hyungi** [comment]
오오오 좋은 지적 감사....!!!

**Comment by hyungi** [comment]
stackoverflow 에서 찾아보니까 이런식으로 해결하면 될듯..!

def get_deadline():
    return datetime.today() + timedelta(days=20)

class Bill(models.Model):
    name = models.CharField(max_length=50)
    customer = models.ForeignKey(User, related_name='bills')
    date = models.DateField(default=datetime.today)
    deadline = models.DateField(default=get_deadline)

[링크!](https://stackoverflow.com/questions/2199013/how-can-my-django-model-datefield-add-30-days-to-the-provided-value)

**Comment by itsnamgyu** [comment]
해결뭬앤
